import type { Metadata } from "next";
import FooterGraffiti from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
      <main
        className={` antialiased bg-black`}
      >
        <Navbar />
        {children}
        <FooterGraffiti />
      </main>
  
  );
}
