import type { Metadata } from "next";
import { Figtree, Bebas_Neue, Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import FooterGraffiti from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas-neue",
  display: "swap",
});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", figtree.variable)}>
      <body
        className={`${raleway.variable} ${bebasNeue.variable} antialiased bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
