import Navbar from "@/components/layout/navbar";
import PageShell from "@/components/shared/PageShell";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CollectionLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={` antialiased bg-black`}>
   
        <Navbar />
        {children}
        <div className="w-full absolute bottom-0"></div>

    </main>
  );
}
